### PR TITLE
test

### PR DESCRIPTION
**Pull request by alexcrichton**

### CODE REVIEW

**Comment by alexcrichton** [comment]
@brson: r+ 8738cca

**Comment by brson** [comment]
:hourglass: Testing commit 8738cca with merge cbae8ec...

**Comment by brson** [comment]
:sunny: Test successful - [auto-bsd-64-opt](http://54.176.156.253//builders/auto-bsd-64-opt/builds/11), [auto-linux-32-nopt-t](http://54.176.156.253//builders/auto-linux-32-nopt-t/builds/11), [auto-linux-32-opt](http://54.176.156.253//builders/auto-linux-32-opt/builds/11), [auto-linux-64-nopt-t](http://54.176.156.253//builders/auto-linux-64-nopt-t/builds/11), [auto-linux-64-opt](http://54.176.156.253//builders/auto-linux-64-opt/builds/11), [auto-linux-64-x-android-t](http://54.176.156.253//builders/auto-linux-64-x-android-t/builds/16), [auto-win-32-nopt-t](http://54.176.156.253//builders/auto-win-32-nopt-t/builds/15), [auto-win-32-opt](http://54.176.156.253//builders/auto-win-32-opt/builds/26), [auto-win-64-nopt-t](http://54.176.156.253//builders/auto-win-64-nopt-t/builds/20), [auto-win-64-opt](http://54.176.156.253//builders/auto-win-64-opt/builds/31)

**Comment by alexcrichton** [comment]
<3

**Pull request merged**
